package com.contract.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class ContractState implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_state.conNum
     *
     * @mbggenerated
     */
    private String connum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_state.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_state.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_state.conNum
     *
     * @return the value of contract_state.conNum
     *
     * @mbggenerated
     */
    public String getConnum() {
        return connum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_state.conNum
     *
     * @param connum the value for contract_state.conNum
     *
     * @mbggenerated
     */
    public void setConnum(String connum) {
        this.connum = connum == null ? null : connum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_state.type
     *
     * @return the value of contract_state.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_state.type
     *
     * @param type the value for contract_state.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_state.time
     *
     * @return the value of contract_state.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_state.time
     *
     * @param time the value for contract_state.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}