package com.contract.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class ContractAttachment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_attachment.conNum
     *
     * @mbggenerated
     */
    private String connum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_attachment.fileName
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_attachment.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_attachment.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_attachment.uploadTme
     *
     * @mbggenerated
     */
    private Date uploadtme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract_attachment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_attachment.conNum
     *
     * @return the value of contract_attachment.conNum
     *
     * @mbggenerated
     */
    public String getConnum() {
        return connum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_attachment.conNum
     *
     * @param connum the value for contract_attachment.conNum
     *
     * @mbggenerated
     */
    public void setConnum(String connum) {
        this.connum = connum == null ? null : connum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_attachment.fileName
     *
     * @return the value of contract_attachment.fileName
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_attachment.fileName
     *
     * @param filename the value for contract_attachment.fileName
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_attachment.path
     *
     * @return the value of contract_attachment.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_attachment.path
     *
     * @param path the value for contract_attachment.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_attachment.type
     *
     * @return the value of contract_attachment.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_attachment.type
     *
     * @param type the value for contract_attachment.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_attachment.uploadTme
     *
     * @return the value of contract_attachment.uploadTme
     *
     * @mbggenerated
     */
    public Date getUploadtme() {
        return uploadtme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_attachment.uploadTme
     *
     * @param uploadtme the value for contract_attachment.uploadTme
     *
     * @mbggenerated
     */
    public void setUploadtme(Date uploadtme) {
        this.uploadtme = uploadtme;
    }
}