package com.contract.mybatis.entity;

import java.io.Serializable;

public class ContractProcessKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_process.conNum
     *
     * @mbggenerated
     */
    private String connum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_process.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_process.userNum
     *
     * @mbggenerated
     */
    private String usernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract_process
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_process.conNum
     *
     * @return the value of contract_process.conNum
     *
     * @mbggenerated
     */
    public String getConnum() {
        return connum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_process.conNum
     *
     * @param connum the value for contract_process.conNum
     *
     * @mbggenerated
     */
    public void setConnum(String connum) {
        this.connum = connum == null ? null : connum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_process.type
     *
     * @return the value of contract_process.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_process.type
     *
     * @param type the value for contract_process.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_process.userNum
     *
     * @return the value of contract_process.userNum
     *
     * @mbggenerated
     */
    public String getUsernum() {
        return usernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_process.userNum
     *
     * @param usernum the value for contract_process.userNum
     *
     * @mbggenerated
     */
    public void setUsernum(String usernum) {
        this.usernum = usernum == null ? null : usernum.trim();
    }
}