package com.contract.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class Contract implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.num
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.customer
     *
     * @mbggenerated
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.beginTime
     *
     * @mbggenerated
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.userNum
     *
     * @mbggenerated
     */
    private String usernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.num
     *
     * @return the value of contract.num
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.num
     *
     * @param num the value for contract.num
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.name
     *
     * @return the value of contract.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.name
     *
     * @param name the value for contract.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.customer
     *
     * @return the value of contract.customer
     *
     * @mbggenerated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.customer
     *
     * @param customer the value for contract.customer
     *
     * @mbggenerated
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.beginTime
     *
     * @return the value of contract.beginTime
     *
     * @mbggenerated
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.beginTime
     *
     * @param begintime the value for contract.beginTime
     *
     * @mbggenerated
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.endTime
     *
     * @return the value of contract.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.endTime
     *
     * @param endtime the value for contract.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.userNum
     *
     * @return the value of contract.userNum
     *
     * @mbggenerated
     */
    public String getUsernum() {
        return usernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.userNum
     *
     * @param usernum the value for contract.userNum
     *
     * @mbggenerated
     */
    public void setUsernum(String usernum) {
        this.usernum = usernum == null ? null : usernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.content
     *
     * @return the value of contract.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.content
     *
     * @param content the value for contract.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}