package com.contract.mybatis.entity;

import java.io.Serializable;

public class Right implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.userNum
     *
     * @mbggenerated
     */
    private String usernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.roleName
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table right
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.userNum
     *
     * @return the value of right.userNum
     *
     * @mbggenerated
     */
    public String getUsernum() {
        return usernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.userNum
     *
     * @param usernum the value for right.userNum
     *
     * @mbggenerated
     */
    public void setUsernum(String usernum) {
        this.usernum = usernum == null ? null : usernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.roleName
     *
     * @return the value of right.roleName
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.roleName
     *
     * @param rolename the value for right.roleName
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.description
     *
     * @return the value of right.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.description
     *
     * @param description the value for right.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}