package com.contract.mybatis.dao;

import com.contract.mybatis.entity.ContractState;
import com.contract.mybatis.entity.ContractStateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int countByExample(ContractStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int deleteByExample(ContractStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String connum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int insert(ContractState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int insertSelective(ContractState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    List<ContractState> selectByExample(ContractStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    ContractState selectByPrimaryKey(String connum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ContractState record, @Param("example") ContractStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ContractState record, @Param("example") ContractStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ContractState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ContractState record);
}