package com.contract.mybatis.dao;

import com.contract.mybatis.entity.ContractAttachment;
import com.contract.mybatis.entity.ContractAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbggenerated
     */
    int countByExample(ContractAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbggenerated
     */
    int deleteByExample(ContractAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbggenerated
     */
    int insert(ContractAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbggenerated
     */
    int insertSelective(ContractAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbggenerated
     */
    List<ContractAttachment> selectByExample(ContractAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ContractAttachment record, @Param("example") ContractAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ContractAttachment record, @Param("example") ContractAttachmentExample example);
}