package com.contract.mybatis.dao;

import com.contract.mybatis.entity.SClass;
import com.contract.mybatis.entity.SClassExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int countByExample(SClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int deleteByExample(SClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String classno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int insert(SClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int insertSelective(SClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    List<SClass> selectByExample(SClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    SClass selectByPrimaryKey(String classno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SClass record, @Param("example") SClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SClass record, @Param("example") SClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SClass record);
}